# -*- coding: utf-8 -*-
"""Nishanth Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pvZ4HbMPK4eVboq2M2t0x9vtZariQ0_
"""

import requests

def get_weather(city):
    API_KEY = 'ad142619439cc8efa92fab327198f2ec'
    base_url = "https://api.openweathermap.org/data/2.5/weather"

    params = {
        'q': city,
        'appid': API_KEY,
        'units': 'metric'  # for Celsius
    }

    response = requests.get(base_url, params=params)

    if response.status_code == 200:
        data = response.json()
        print(f"\n📍 Weather in {data['name']}, {data['sys']['country']}")
        print(f"🌤️ Condition: {data['weather'][0]['description'].title()}")
        print(f"🌡️ Temperature: {data['main']['temp']}°C")
        print(f"💧 Humidity: {data['main']['humidity']}%")
        print(f"🌬️ Wind Speed: {data['wind']['speed']} m/s")
    else:
        print("❌ City not found or error fetching data. Please try again.")

# Ask user for city name
city_name = input("Enter city name: ")
get_weather(city_name)